[package]
name = "kairotui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = {version = "0.29.0", features = ["all-widgets"] }
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
serde_millis = "0.1.1"
tachyonfx = "0.15.0"
